<?php if (!isset($this->error)): ?>
<div class="header"><h3>Add item</h3></div>
<form action="<?php print $this->form_action; ?>" name="f_insert" method="post">
<table border="0" cellspacing="0" cellspading="0">
<tr><td class="meta">Name</td><td><input type='text' name='s_Name' value=''></td></tr>
<tr><td class="meta">Alias</td><td><input type='text' name='s_Alias' value=''></td></tr>
<tr><td class="meta">Date_creation</td><td><input type='text' name='s_Date_creation' value=''></td></tr>
<tr><td class="meta">Date_modification</td><td><select name='s_Date_modification_year[]'>
<option value='2000' >2000</option>
<option value='2001' >2001</option>
<option value='2002' >2002</option>
<option value='2003' >2003</option>
<option value='2004' >2004</option>
<option value='2005' >2005</option>
<option value='2006' >2006</option>
<option value='2007' >2007</option>
<option value='2008' >2008</option>
<option value='2009' selected>2009</option>
</select>.<select name='s_Date_modification_mon[]'>
<option value='1' >01</option>
<option value='2' >02</option>
<option value='3' >03</option>
<option value='4' selected>04</option>
<option value='5' >05</option>
<option value='6' >06</option>
<option value='7' >07</option>
<option value='8' >08</option>
<option value='9' >09</option>
<option value='10' >10</option>
<option value='11' >11</option>
<option value='12' >12</option>
</select>.<select name='s_Date_modification_day[]'>
<option value='1' >01</option>
<option value='2' >02</option>
<option value='3' >03</option>
<option value='4' >04</option>
<option value='5' >05</option>
<option value='6' >06</option>
<option value='7' >07</option>
<option value='8' >08</option>
<option value='9' >09</option>
<option value='10' selected>10</option>
<option value='11' >11</option>
<option value='12' >12</option>
<option value='13' >13</option>
<option value='14' >14</option>
<option value='15' >15</option>
<option value='16' >16</option>
<option value='17' >17</option>
<option value='18' >18</option>
<option value='19' >19</option>
<option value='20' >20</option>
<option value='21' >21</option>
<option value='22' >22</option>
<option value='23' >23</option>
<option value='24' >24</option>
<option value='25' >25</option>
<option value='26' >26</option>
<option value='27' >27</option>
<option value='28' >28</option>
<option value='29' >29</option>
<option value='30' >30</option>
<option value='31' >31</option>
</select> // <select name='s_Date_modification_hour[]'>
<option value='0' selected>00</option>
<option value='1' >01</option>
<option value='2' >02</option>
<option value='3' >03</option>
<option value='4' >04</option>
<option value='5' >05</option>
<option value='6' >06</option>
<option value='7' >07</option>
<option value='8' >08</option>
<option value='9' >09</option>
<option value='10' >10</option>
<option value='11' >11</option>
<option value='12' >12</option>
<option value='13' >13</option>
<option value='14' >14</option>
<option value='15' >15</option>
<option value='16' >16</option>
<option value='17' >17</option>
<option value='18' >18</option>
<option value='19' >19</option>
<option value='20' >20</option>
<option value='21' >21</option>
<option value='22' >22</option>
<option value='23' >23</option>
</select>:<select name='s_Date_modification_min[]'>
<option value='0' >00</option>
<option value='1' >01</option>
<option value='2' >02</option>
<option value='3' >03</option>
<option value='4' >04</option>
<option value='5' >05</option>
<option value='6' >06</option>
<option value='7' >07</option>
<option value='8' >08</option>
<option value='9' >09</option>
<option value='10' >10</option>
<option value='11' >11</option>
<option value='12' >12</option>
<option value='13' >13</option>
<option value='14' >14</option>
<option value='15' >15</option>
<option value='16' >16</option>
<option value='17' >17</option>
<option value='18' >18</option>
<option value='19' >19</option>
<option value='20' >20</option>
<option value='21' selected>21</option>
<option value='22' >22</option>
<option value='23' >23</option>
<option value='24' >24</option>
<option value='25' >25</option>
<option value='26' >26</option>
<option value='27' >27</option>
<option value='28' >28</option>
<option value='29' >29</option>
<option value='30' >30</option>
<option value='31' >31</option>
<option value='32' >32</option>
<option value='33' >33</option>
<option value='34' >34</option>
<option value='35' >35</option>
<option value='36' >36</option>
<option value='37' >37</option>
<option value='38' >38</option>
<option value='39' >39</option>
<option value='40' >40</option>
<option value='41' >41</option>
<option value='42' >42</option>
<option value='43' >43</option>
<option value='44' >44</option>
<option value='45' >45</option>
<option value='46' >46</option>
<option value='47' >47</option>
<option value='48' >48</option>
<option value='49' >49</option>
<option value='50' >50</option>
<option value='51' >51</option>
<option value='52' >52</option>
<option value='53' >53</option>
<option value='54' >54</option>
<option value='55' >55</option>
<option value='56' >56</option>
<option value='57' >57</option>
<option value='58' >58</option>
<option value='59' >59</option>
</select>:<select name='s_Date_modification_sec[]'>
<option value='0' >00</option>
<option value='1' >01</option>
<option value='2' >02</option>
<option value='3' >03</option>
<option value='4' >04</option>
<option value='5' >05</option>
<option value='6' >06</option>
<option value='7' >07</option>
<option value='8' >08</option>
<option value='9' >09</option>
<option value='10' >10</option>
<option value='11' >11</option>
<option value='12' >12</option>
<option value='13' >13</option>
<option value='14' >14</option>
<option value='15' >15</option>
<option value='16' >16</option>
<option value='17' selected>17</option>
<option value='18' >18</option>
<option value='19' >19</option>
<option value='20' >20</option>
<option value='21' >21</option>
<option value='22' >22</option>
<option value='23' >23</option>
<option value='24' >24</option>
<option value='25' >25</option>
<option value='26' >26</option>
<option value='27' >27</option>
<option value='28' >28</option>
<option value='29' >29</option>
<option value='30' >30</option>
<option value='31' >31</option>
<option value='32' >32</option>
<option value='33' >33</option>
<option value='34' >34</option>
<option value='35' >35</option>
<option value='36' >36</option>
<option value='37' >37</option>
<option value='38' >38</option>
<option value='39' >39</option>
<option value='40' >40</option>
<option value='41' >41</option>
<option value='42' >42</option>
<option value='43' >43</option>
<option value='44' >44</option>
<option value='45' >45</option>
<option value='46' >46</option>
<option value='47' >47</option>
<option value='48' >48</option>
<option value='49' >49</option>
<option value='50' >50</option>
<option value='51' >51</option>
<option value='52' >52</option>
<option value='53' >53</option>
<option value='54' >54</option>
<option value='55' >55</option>
<option value='56' >56</option>
<option value='57' >57</option>
<option value='58' >58</option>
<option value='59' >59</option>
</select></td></tr>
<tr><td class="meta">Description</td><td><textarea name='s_Description'></textarea></td></tr>
<tr><td class="meta">DefaultPhotoID</td><td>
            <select name='s_DefaultPhotoID'>
            <?php foreach($this->options_DefaultPhotoID as $option): ?>
                <option value='<?php print $option['ID']; ?>'><?php print $option['Description']; ?></option>
            <?php endforeach; ?>
            </select></td></tr>
<tr><td class="meta">Raiting</td><td><input type='text' name='s_Raiting' value=''></td></tr>
<tr><td class="meta">Hidden</td><td><input type='checkbox' name='s_Hidden' ></td></tr>

<tr><td></td><td><br/><input type="submit" name="f_insert_submit" value="Insert"/></td></tr>
</form>
</table>
<?php else: ?>
<?php print $this->error; ?>
<?php endif; ?>