<?php if (isset($this->notemplate)): ?>
<?php print $this->layout()->content; ?>
<?php else: ?>
<html>
<head>
<title>Adminzone</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="http://taryk/admin/public/design/css/style.css" media="screen" rel="stylesheet" type="text/css" />
<?php if ($this->head_link2) { print $this->head_link2; } ?>
<?php print $this->jQuery()->enable(); ?>
<?php if ($this->head_script2) { print $this->head_script2; } ?>
<script language="javascript" src="http://taryk/admin/public/design/js/script.js"></script>
</head>
<body>
<div id="top"><?php print $this->top; ?></div>
<div id="content">
    <div id="menu">
        <div id="left_toolbar">+</div>
        <div id="left_menu">
            <div class="hello"><?php if (isset($this->user)) { ?>Hello, <?php print $this->user->Username ?>!<br /><br /><?php } ?></div>

            <?php $nofirst=false; ?>

            <?php foreach($this->mainmenu as $item): ?>

            <?php if ($item['Controller']=='index' or $item['Controller']=='home'): ?>
            <?php if ($nofirst) { ?>
            </div></div>
            <?php } else { $nofirst=true; } ?>
            <div>

            <div class="menuModule" onclick="menuToogle(<?php print $item['ID']; ?>)" id="main<?php print $item['ID']; ?>"><?php print $item['Module']; ?></div>
            <div class="menuSub" id="sub<?php print $item['ID']; ?>">
            <?php endif; ?>

            <a href="<?php print $this->fullurl.$item['Link']; ?>" alt="<?php print $item['Description']; ?>"><?php print $item['Name']; ?></a><br />

            <?php endforeach; ?></div>
            </div>
        </div>
    </div>
    <div id="main"><?php print $this->layout()->content; ?></div>
</div>
<div id="bottom"><?php print $this->bottom; ?></div>
</body>
</html>
<?php endif; ?>